name: Build and Version

on:
  push:
    branches:
      - main


jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        run: dotnet tool install -g GitVersion.Tool
      
      - name: Determine version
        id: gitversion
        run: echo "VERSION=$(dotnet-gitversion /output json | jq -r .FullSemVer)" >> $GITHUB_ENV
      
      - name: Build project
        run: dotnet build -c Release /p:Version=$VERSION
      
      - name: Tag and Push Release
        run: |
          git tag v$VERSION
          git push origin v$VERSION

  docker:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build and tag Docker image
        run: |
          docker build -t myapp:$VERSION .
          docker tag myapp:$VERSION myrepo/myapp:$VERSION
      
      - name: Push Docker image
        run: docker push myrepo/myapp:$VERSION
